### ISSUE TITLE
Format type alias properly

### ISSUE THREAD

**Issue by cironunes** [angular/clang-format#22] opened 2015-12-14 18:21 UTC
See https://github.com/angular/angular/pull/5880#discussion-diff-47526036

**Comment by mprobst** [comment] 2016-04-18 22:36
The commit in question can no longer be fund by Github, and I cannot reproduce by trying something that looks like it could have been the issue :-(

@cironunes do you remember what exactly the code was that didn't format properly?

**Comment by cironunes** [comment] 2016-04-22 16:08
Sorry, but I don't remember as well. Maybe this can give you some insight? https://travis-ci.org/angular/angular/jobs/96761613#L291

**Comment by mprobst** [comment] 2016-04-22 16:15
Nope, not really. Let's close this as obsolete, there have been some fixes to typedefs and generally they look fine to me these days. If it comes up again, we can re-file.

**Closed as completed by mprobst** 2016-04-22 16:15 UTC
